### ISSUE TITLE
是否能添加SQLite3支持

### ISSUE THREAD

**Issue by TorstenLiu** [kokororin/typecho-plugin-Access#15]
这个插件非常棒！非常恳切的希望大佬能增加SQLite支持，目前只支持Mysql。

**Comment by kokororin** [comment]
你可以试试手动创建表
https://github.com/kokororin/typecho-plugin-Access/blob/master/sql/Mysql.sql
不太懂SQLite

**Comment by TorstenLiu** [comment]
Thank You Very Much
我也是SQLite小白
也不太懂，不管如何还是很感谢你

**Comment by izhizheng** [comment]
我做了一下 SQLite3 的适配，可以使用，但还有个“Database Query Error”的问题，不影响使用，具体参考  https://www.izhizheng.net/archives/36/

**Comment by kokororin** [comment]
@izhizheng 测试了一下，没有“Database Query Error”，如果方便的话可以提个PR喔

**Comment by izhizheng** [comment]
好的
