### ISSUE TITLE
关于“昨天”的数据统计显示和“今天”完全相同的问题

### ISSUE THREAD

**Issue by iblueer** [kokororin/typecho-plugin-Access#16]
12月20日，我博客访问量只有50左右，显示“今天50；昨天50”。
12月21日，我博客访问量950左右，显示“今天950；昨天950”。

是不是 访问概览 里面的内容有问题？

<img width="1190" alt="2017-12-21 19 05 29" src="https://user-images.githubusercontent.com/3581944/34253300-f46e6450-e681-11e7-80f4-58a391ee3af3.png">

**Comment by kokororin** [comment]
感谢反馈已修复 ∪･ω･∪
