### ISSUE TITLE
在linux下会出现Database Query Error

### ISSUE THREAD

**Issue by yuangu** [kokororin/typecho-plugin-Access#17]
平台：ubuntu16.04
php版本：PHP 7.0.22
http服务器nginx/1.10.3

**Comment by kokororin** [comment]
不知道解决了没有？可以打开Typecho调试模式看看。

**Comment by yuangu** [comment]
解决了，我发现是其它插件引起的。在win上没有装其它插件。就正常了。可以close此issue了
