### ISSUE TITLE
关于“昨天”和“今天”的 UV IP 统计不正确的问题

### ISSUE THREAD

**Issue by izhizheng** [kokororin/typecho-plugin-Access#18]
查看 Access_Core.php，发现“昨天”和“今天”的 UV IP 是通过分时段统计再相加得来的。这样，各小时内重复的数据会计算多次，造成错误。比如一个 IP 192.168.1.1 每个小时都访问网站，按理来说，一整天只算一次，但按现在累加的方法，这一天统计的 ip 192.168.1.1 会是 24 个。不知道我这样理解对不对？
<img width="554" alt="2018-01-25_174737" src="https://user-images.githubusercontent.com/27559529/35381616-dc06c132-01f7-11e8-9fce-d55096c9d22c.png">

**Comment by kokororin** [comment]
感谢，已修复
