### ISSUE TITLE
Referer来路不对啊

### ISSUE THREAD

**Issue by k649781645** [kokororin/typecho-plugin-Access#21]
所有来路都是受访页面本身

**Comment by kokororin** [comment]
没有这个问题

**Comment by k649781645** [comment]
这个是我正常访问日志。发现所有来路都是本身页面后，我测试过点击站内链接，打开点击页面后记录的来路依然是点击受访的页面本身（期望是原触发点击的页面URL）
![8888](https://user-images.githubusercontent.com/19792713/35467714-0bc37a0e-034d-11e8-8a80-520db1c31cae.jpg)

**Comment by kokororin** [comment]
你的网站是否开启了[Referrer Policy](https://imququ.com/post/referrer-policy.html)
我这里确实没有问题，也没有其他人反映过有这个问题..
![image](https://user-images.githubusercontent.com/10093992/35467957-c33ea692-0350-11e8-91d7-5f37ab906398.png)

**Comment by k649781645** [comment]
用的阿里云虚机。我搭建本地环境测试下，看是否主机配置上的问题。谢谢！

**Comment by k649781645** [comment]
本地验证了没问题。确实是阿里虚机的问题。好大一个坑。。。

**Comment by k649781645** [comment]
想了下阿里不应该犯这么低级的错误，于是把插件禁用(选择删除数据、先备份了表)。然后重新启用插件发现正常了。然后对比了现在的表结构和老的。发现有些出入，但看起来也不应该造成这问题才对。就先不管了，反正问题解决。
![qq 20180127120203](https://user-images.githubusercontent.com/19792713/35468517-8f19e502-035a-11e8-9126-ccc78ef6f8e2.jpg)
