### ISSUE TITLE
数据表建立失败，插件启用失败

### ISSUE THREAD

**Issue by EwigMidori** [kokororin/typecho-plugin-Access#27]
数据表建立失败，插件启用失败，错误信息：SQLSTATE[HY000]: General error: 1 cannot commit - no transaction is active。

但是查看数据库（注：SQLite），数据表是存在的。在两个Typecho站点测试，得到同样的错误。
重新启用一次，之后可以正常使用。

**Comment by kokororin** [comment]
SQLite是有各种问题，欢迎PR
