### ISSUE TITLE
插件用不了，只有我遇到这个问题？

### ISSUE THREAD

**Issue by scxingm** [kokororin/typecho-plugin-Access#30]
Warning: require_once(/www/wwwroot/typecho//usr/plugins/Access/page/console.php): failed to open stream: No such file or directory in /www/wwwroot/typecho/admin/extending.php on line 13

Fatal error: require_once(): Failed opening required '/www/wwwroot/typecho//usr/plugins/Access/page/console.php' (include_path='.:/www/server/php/70/lib/php:/www/wwwroot/typecho/var:/www/wwwroot/typecho/usr/plugins') in /www/wwwroot/typecho/admin/extending.php on line 13

**Comment by xiaoyiya** [comment]
我使用是正常的

**Comment by tinymins** [comment]
无法重现，请检查 `console.php` 文件 php 服务是否有读权限
