### ISSUE TITLE
疑似IPv6兼容问题

### ISSUE THREAD

**Issue by lydasia** [kokororin/typecho-plugin-Access#31]
升级到2.0.2之后IP地址一栏经常有记录显示0.0.0.0，一直没有找到原因。近期突然意识到原来有很多IPv6的访客记录的，自升级之后就没有出现过，因此怀疑是IPv6访客记录显示为0.0.0.0。尚未对照服务器log验证，有时间我会确认一下的。如图：
https://i.imgur.com/zZxsIeJ.png

**Comment by FSpark** [comment]
亲测，对照了log，IPv6访客记录的确会显示为0.0.0.0。。求修复

**Comment by Anankke** [comment]
https://github.com/Anankke/typecho-plugin-Access
，，，

**Comment by tinymins** [comment]
已支持
