### ISSUE TITLE
能否支持一下 CDN 转发的 IP 地址？

### ISSUE THREAD

**Issue by Dreamer-Paul** [kokororin/typecho-plugin-Access#33]
由于我的网站采用了 CloudFlare 作为防护，故本插件获得的原站 IP 都是 CF 的节点。我自己倒是发现 `HTTP_X_FORWARDED_FOR` 头是可以获取真实用户 IP 的，不知作者能否让插件支持一下~

**Comment by kokororin** [comment]
https://kotori.love/archives/typecho-plugin-access.html 评论里有

**Comment by Innei** [comment]
网站挂了. 请问你最新的博客是..

**Comment by kokororin** [comment]
> 网站挂了. 请问你最新的博客是..

https://www.typecho.wiki/archives/typecho-configuring-cdn-to-get-visitors-real-ip.html

**Comment by Captain-ZR** [comment]
你好，我好像看不到你博客中的关于获取真实ip的评论，请问是我操作的问题吗，还是您删除了

**Comment by Captain-ZR** [comment]
> 你好，我好像看不到你博客中的关于获取真实ip的评论，请问是我操作的问题吗，还是您删除了

解决了，以下为解决步骤
在typecho根目录中的config.inc.php文件中添加以下两个部分

### 1. 在`config.inc.php`文件前部添加define，以下三个三选一即可
```
define('__TYPECHO_IP_SOURCE__', 'HTTP_ALI_CDN_REAL_IP');
```
或
```
define('__TYPECHO_IP_SOURCE__','HTTP_CLIENT_IP');
```
或
```
define('__TYPECHO_IP_SOURCE__','HTTP_X_FORWARDED_FOR');
```

### 2. 在`config.inc.php`文件最后加上
```
if (isset($_SERVER['HTTP_CF_CONNECTING_IP'])) $_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];?>
```

以上两步完成应该就可以了，如果没效果试试重新启动`php-fpm`
注意：要两步都完成才可以

> 我在网上查找相关资料的时候，很多都是说像第一步中添加一个define即可；也有说加上一句类似第二步中的if语句。网上的说法都是两个步骤之一完成就可以了，但是我试过都没效果。我是刚好运气好把两步都一起做了才有效果，至于原理我也不懂，本人对相关技术不了解
