### ISSUE TITLE
数据表建立失败，插件启用失败，错误信息：Unknown storage engine 'InnoDB'。

### ISSUE THREAD

**Issue by Nliver** [kokororin/typecho-plugin-Access#34]
数据表建立失败，插件启用失败，错误信息：Unknown storage engine 'InnoDB'。
看了教程似乎是要开启default-storage-engine=INNODB ，但是我已经开了，依旧不行，不知道为啥

**Comment by tinymins** [comment]
MySQL 配置问题，https://stackoverflow.com/questions/4757589/how-to-enable-innodb-in-mysql
