### ISSUE TITLE
Access控制台用户权限问题

### ISSUE THREAD

**Issue by yishuihan1203** [kokororin/typecho-plugin-Access#35]
普通的注册用户登录后台也能在控制台看到accss控制台选项并且查看访客记录，感觉最好默认只有管理员可以看到，其它权限账户不显示。

**Comment by SteamFinder** [comment]
同，我也发现了这个问题

**Comment by xiaoyiya** [comment]
确实存在，但是作者似乎不会更新了。只能期待有其他人会分支维护

**Comment by kokororin** [comment]
https://github.com/kokororin/typecho-plugin-Access/blob/master/Plugin.php#L25 `subscriber`改为`administrator`即可

**Comment by SteamFinder** [comment]
感谢
