### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by CberYellowstone** [kokororin/typecho-plugin-Access#43]
希望能加入 不记录特定ip的功能
我开启了网站检查
插件每次都会把检查的bot认作真人

**Comment by kokororin** [comment]
PRs welcomed

**Comment by Big-god-Yin** [comment]
感觉这个功能很有用，我统计里面一长串127，人都麻了

**Comment by Winyer** [comment]
+1，自己的地址也记录进去有点麻

**Comment by tinymins** [comment]
已支持, https://github.com/kokororin/typecho-plugin-Access/commit/de75cbb7ace18455b3316d7894982c28c910bf11

**Comment by tinymins** [comment]
![image](https://user-images.githubusercontent.com/1808990/205843488-da35c703-49f3-4e1a-a1d7-fda8107b06c3.png)
