### ISSUE TITLE
Access插件 日志分页 和ip记录

### ISSUE THREAD

**Issue by hesperup** [kokororin/typecho-plugin-Access#47]
日志分页的链接有问题。
网站开启了 Cloudflare 的DNS 代理。 IP 都显示的是美国 CloudFlare公司CDN节点IP

**Comment by kokororin** [comment]
CDN问题已有相关issue，请自行翻阅

**Comment by hesperup** [comment]
config.inc.php 中配置
define('__TYPECHO_IP_SOURCE__','HTTP_CF_CONNECTING_IP');
