### ISSUE TITLE
能够让其他用户看不到这个插件吗？

### ISSUE THREAD

**Issue by Winyer** [kokororin/typecho-plugin-Access#53]
我发现每个用户组的都能看到这个插件，换句话说，只要是用户就没有看不到这个插件的，虽然用户不能对日志进行删除等更改，但是访问数据他们也能看到就很不爽，有没有办法让除管理员以外的用户组不能看到这个插件的显示呢？

**Comment by kokororin** [comment]
duplicated as #35
