### ISSUE TITLE
访问概览打不开

### ISSUE THREAD

**Issue by zsyq** [kokororin/typecho-plugin-Access#66]
访问日志可以查看，访问概览打不开，显示 Call to undefined function cal_days_in_month() 请问这个如何解决？

**Comment by Yang16634** [comment]
你好，打开Access文件夹下的Access_Core.php
找到protected function parseOverview()，在”{“后面加上

    function cal_days_in_month($calendar, $month, $year) 
    { 
        return date('t', mktime(0, 0, 0, $month, 1, $year)); 
    }

找到$monthDays = cal_days_in_month(CAL_GREGORIAN, intval($month), intval($year));
在CAL_GREGORIAN两边加上单引号，如下
$monthDays = cal_days_in_month('CAL_GREGORIAN', intval($month), intval($year));
问题解决。

**Comment by tinymins** [comment]
fixed, https://github.com/kokororin/typecho-plugin-Access/commit/e33a5cf0b4b17893fdb1f938a1d20a42eedab5f8
