### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by zsyq** [kokororin/typecho-plugin-Access#67]
之前正常使用，升级Typecho1.2版本后就无法使用了，Php版本是7.2。启用插件显示  Argument 1 passed to _t() must be of the type string, null given, called in /www/wwwroot/askahh.com/usr/plugins/Access/Plugin.php on line 32 请问有解决方法吗？谢谢。

**Comment by MUKAPP** [comment]
我也出现了

**Comment by tinymins** [comment]
删除数据表重新启用之后就正常了，估计是哪里升级不兼容导致的

**Comment by tinymins** [comment]
@zsyq @MUKAPP 各位请使用最新版本再试一下，看看问题是否已解决？

**Comment by MUKAPP** [comment]
> @zsyq @MUKAPP 各位请使用最新版本再试一下，看看问题是否已解决？

可以了，但是这一堆选项咋办（
![image](https://user-images.githubusercontent.com/41848070/206441517-7d6a4ccc-dbbc-4a92-a84c-44abe060b697.png)

**Comment by tinymins** [comment]
> > @zsyq @MUKAPP 各位请使用最新版本再试一下，看看问题是否已解决？
> 
> 可以了，但是这一堆选项咋办（ ![image](https://user-images.githubusercontent.com/41848070/206441517-7d6a4ccc-dbbc-4a92-a84c-44abe060b697.png)

禁用再重新启用，`typecho` 启用插件出现异常会导致这个问题

**Comment by zsyq** [comment]
> 

https://wasabi.fun/8448.html 可以看看这篇文章，亲测可用。

**Comment by MUKAPP** [comment]
> 禁用再重新启用，`typecho` 启用插件出现异常会导致这个问题

可以了，感谢大佬
