### ISSUE TITLE
升级后问题

### ISSUE THREAD

**Issue by nuoxi4n** [kokororin/typecho-plugin-Access#71]
旧版本2.0.2下载最新的master，然后启用插件显示：Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8404992 bytes) in /wwwroot/web.com/var/Typecho/Db/Adapter/Pdo.php on line 102

**Comment by tinymins** [comment]
看起来是老数据库升级问题，数据量太大了，可以删除旧数据，或者等对老数据进行分批升级（可以做但是还没有的功能）

**Comment by nuoxi4n** [comment]
@tinymins 正解

**Comment by tinymins** [comment]
应该就是一个for循环的事情，不过还得考虑php超时问题… 要做成单次如果超时下次断点处继续才算完美，要不先加个for试试看

**Comment by tinymins** [comment]
已实现，正在自己网站上测试： https://github.com/kokororin/typecho-plugin-Access/tree/3b478634bb1bd184c03ecbe5a300b33218d685fb

![image](https://user-images.githubusercontent.com/1808990/205988047-9802f3c5-605f-4ee4-aa8e-904136bc358c.png)

**Comment by wasas** [comment]
新版和 SimpleAdmin 冲突, 控制台一直 loading...

**Comment by tinymins** [comment]
> 新版和 SimpleAdmin 冲突, 控制台一直 loading...

@wasas  试了下没有发现问题 ~~，样式倒是崩的厉害，之前样式崩么？按理说也崩的很毕竟没改过界面~~

并且最新版已修复样式问题：

![image](https://user-images.githubusercontent.com/1808990/206175189-ca20ce4c-af29-4e9f-be8d-a47aa9375247.png)

**Comment by tinymins** [comment]
> 新版和 SimpleAdmin 冲突, 控制台一直 loading...

可以更新到最新试试，我看了下代码，可能是同步请求太多了导致数据库阻塞。

来源： https://github.com/kokororin/typecho-plugin-Access/commit/bbd8016675a931556b7d535fb6715a7d8801b67a
修改： https://github.com/kokororin/typecho-plugin-Access/commit/fa704a11e387b6f9b757b9eec112d2a515981aa6

**Comment by tinymins** [comment]
更新：

我发现他有些请求特别慢… 怀疑相关功能数据库没加索引，一会看看…

![image](https://user-images.githubusercontent.com/1808990/206090837-7053c2d1-1c7e-43f6-ae62-3b288fcbeb71.png)

**Comment by wasas** [comment]
> > 新版和 SimpleAdmin 冲突, 控制台一直 loading...
> 
> 可以更新到最新试试，我看了下代码，可能是同步请求太多了导致数据库阻塞。
> 
> 来源： [bbd8016](https://github.com/kokororin/typecho-plugin-Access/commit/bbd8016675a931556b7d535fb6715a7d8801b67a) 修改： [fa704a1](https://github.com/kokororin/typecho-plugin-Access/commit/fa704a11e387b6f9b757b9eec112d2a515981aa6)




感谢开发,感谢回复, 我一个个试的, 3号的最后一个还可以用,
https://github.com/kokororin/typecho-plugin-Access/archive/31302003d4083a56c9b007d6957382fe84c11c77.zip

4号的第一次更改就不能用了,
https://github.com/kokororin/typecho-plugin-Access/archive/eee11fc919dfea3139b35c80d09876851cecdc82.zip

我也不懂程序, 我看了下后台页面里面该插入的 css, js 之类的都是正常存在的, 


最新版的还是有冲突, 好像短暂显示出来过两次, 但强刷几下还是一直 loading...
最新版, 在关闭 SimpleAdmin 后, 访问日志->UA 点击后显示大概 1 秒多的正在获取数据后也没反应了, IP 地址,点击后也同样

我的系统, win 10, 浏览器, Google Chrome 107.0.5304.122（正式版本） （64 位）

**Comment by tinymins** [comment]
> > > 新版和 SimpleAdmin 冲突, 控制台一直 loading...
> > 
> > 
> > 可以更新到最新试试，我看了下代码，可能是同步请求太多了导致数据库阻塞。
> > 来源： [bbd8016](https://github.com/kokororin/typecho-plugin-Access/commit/bbd8016675a931556b7d535fb6715a7d8801b67a) 修改： [fa704a1](https://github.com/kokororin/typecho-plugin-Access/commit/fa704a11e387b6f9b757b9eec112d2a515981aa6)
> 
> 感谢开发,感谢回复, 我一个个试的, 3号的最后一个还可以用, https://github.com/kokororin/typecho-plugin-Access/archive/31302003d4083a56c9b007d6957382fe84c11c77.zip
> 
> 4号的第一次更改就不能用了, https://github.com/kokororin/typecho-plugin-Access/archive/eee11fc919dfea3139b35c80d09876851cecdc82.zip
> 
> 我也不懂程序, 我看了下后台页面里面该插入的 css, js 之类的都是正常存在的,
> 
> 最新版的还是有冲突, 好像短暂显示出来过两次, 但强刷几下还是一直 loading... 最新版, 在关闭 SimpleAdmin 后, 访问日志->UA 点击后显示大概 1 秒多的正在获取数据后也没反应了, IP 地址,点击后也同样
> 
> 我的系统, win 10, 浏览器, Google Chrome 107.0.5304.122（正式版本） （64 位）

@wasas  Windows 的话，可以麻烦帮忙按F12看一下浏览器控制台有什么报错吗？想要复现或者拿到错误信息才知道问题～

**Comment by wasas** [comment]
page\components\object.assgin

-_-..  用这么久浏览器今天才知道可以这样........

上面那个文件夹名写错了,  代码里用的是 object.assign

**Comment by wasas** [comment]
我删除插件的所有数据, 重新下载, 上面的文件名也改成 object.assign, 浏览器也没有报错了.
但是问题都还在,

**Comment by wasas** [comment]
冲突的原因我解决了, 我删除了那个插件的检查更新的代码, 影响到咱们这个统计插件了, 我给它都删除就完事了.
现在剩下的这个应该是本身的问题了, 我搞不懂 -_-..

**Comment by tinymins** [comment]
> 冲突的原因我解决了, 我删除了那个插件的检查更新的代码, 影响到咱们这个统计插件了, 我给它都删除就完事了. 现在剩下的这个应该是本身的问题了, 我搞不懂 -_-..

@wasas 我忽然觉得可能是PHP版本兼容问题，你那边服务器PHP版本是多少，我切换试试

**Comment by tinymins** [comment]
> 冲突的原因我解决了, 我删除了那个插件的检查更新的代码, 影响到咱们这个统计插件了, 我给它都删除就完事了. 现在剩下的这个应该是本身的问题了, 我搞不懂 -_-..

不该冲突啊，我也试着安装了你提到的这个插件，是这个地址嘛 https://github.com/gogobody/SimpleAdmin

**Comment by tinymins** [comment]
@wasas 如果是 PHP 版本问题，我猜是这里导致的，可以帮忙试下吗，把下面位置①那行代码修改成②：

①

https://github.com/kokororin/typecho-plugin-Access/blob/2fc6bcf8813f16a9f8e464c169e4a6ff1998cc38/page/console.php#L26

```php
      <?php include("routes/{$access->action}/index.php") ?>
```

②


```php
      <?php
      if ($access->action === 'logs') {
        include("routes/logs/index.php");
      } else if ($access->action === 'migration') {
        include("routes/migration/index.php");
      } else if ($access->action === 'overview') {
        include("routes/overview/index.php");
      }
      ?>
```

**Comment by tinymins** [comment]
> @tinymins 正解

@nuoxianCN 应该完善的差不多了~

![image](https://user-images.githubusercontent.com/1808990/206366477-45c86380-5e85-46dc-8560-521c816c4307.png)

![image](https://user-images.githubusercontent.com/1808990/206367208-fd10f7b1-a255-4dd0-b90f-5c18564d89c5.png)

**Comment by wasas** [comment]
> > 冲突的原因我解决了, 我删除了那个插件的检查更新的代码, 影响到咱们这个统计插件了, 我给它都删除就完事了. 现在剩下的这个应该是本身的问题了, 我搞不懂 -_-..
> 
> 不该冲突啊，我也试着安装了你提到的这个插件，是这个地址嘛 https://github.com/gogobody/SimpleAdmin

给您添麻烦了, 
是这个地址的, 
冲突是我删除那个插件检测更新的代码造成的, 我已经解决了,

我的 PHP 版本是 7.3.33, 下面那个代码改前和改后都是正常运行的.. 
如果那个 访问日志->UA 是点击后显示所有相同记录的话, 那我这里就是全部正常了, 我之前以为是点击后 弹出那个 UA 的详细信息..
再次感谢你...

**Comment by tinymins** [comment]
> 



> > > 冲突的原因我解决了, 我删除了那个插件的检查更新的代码, 影响到咱们这个统计插件了, 我给它都删除就完事了. 现在剩下的这个应该是本身的问题了, 我搞不懂 -_-..
> > 
> > 
> > 不该冲突啊，我也试着安装了你提到的这个插件，是这个地址嘛 https://github.com/gogobody/SimpleAdmin
> 
> 给您添麻烦了, 是这个地址的, 冲突是我删除那个插件检测更新的代码造成的, 我已经解决了,
> 
> 我的 PHP 版本是 7.3.33, 下面那个代码改前和改后都是正常运行的.. 如果那个 访问日志->UA 是点击后显示所有相同记录的话, 那我这里就是全部正常了, 我之前以为是点击后 弹出那个 UA 的详细信息.. 再次感谢你...

原来是这样，我已经忘记点击可以看UA详情了，后面兼容下这个历史功能，在旁边放个按钮~

**Comment by nuoxianCN** [comment]
![image](https://user-images.githubusercontent.com/56551535/206614943-c3a7ae7d-acf8-4a16-9940-c9b8024a32dd.png)
![image](https://user-images.githubusercontent.com/56551535/206615007-b4b50498-44e8-47b2-8a33-3cfd23244da0.png)

**Comment by nuoxi4n** [comment]
插件启用时没有提示是插件问题还是什么问题

**Comment by tinymins** [comment]
> 



> 插件启用时没有提示是插件问题还是什么问题

请问，遇到什么问题了吗？

**Comment by nuoxi4n** [comment]
如图
![QQ截图20221209110316](https://user-images.githubusercontent.com/56551535/206615583-5092c498-718d-49b5-82ce-df6304dd3153.png)

**Comment by tinymins** [comment]
> 如图 ![QQ截图20221209110316](https://user-images.githubusercontent.com/56551535/206615583-5092c498-718d-49b5-82ce-df6304dd3153.png)

看了下是数据库已存在时候提示语逻辑有遗漏，刚刚已修复，是个无伤大雅的问题，不影响功能~

**Comment by nuoxi4n** [comment]
感觉写入后端数据库信息太多，能不能考虑设计个清除半年后、一年后的数据（例如详细的IP、UA，但保存访问的IP数量等）

**Comment by tinymins** [comment]
> 感觉写入后端数据库信息太多，能不能考虑设计个清除半年后、一年后的数据（例如详细的IP、UA，但保存访问的IP数量等）

我也是觉得存的太多了，所以这两天活了过来，重构日志逻辑，加了批量删除的功能。以及，清除数据但是保留ip数量这个不合理，数据清掉了就没法计算ip数量了，因为无法判断新的ip是否在已经清除的数据里头。

**Comment by tinymins** [comment]
> 感觉写入后端数据库信息太多，能不能考虑设计个清除半年后、一年后的数据（例如详细的IP、UA，但保存访问的IP数量等）

![image](https://user-images.githubusercontent.com/1808990/206616440-2e6a949a-8a8a-4df8-b14b-5e387e2fd416.png)

我是需要这么一个功能，所以这两天狂改了一波实现了。

**Comment by nuoxianCN** [comment]
Good

**Comment by nuoxi4n** [comment]
根据分类选择清除对应的ip段、清除所有认定为爬虫的

**Comment by tinymins** [comment]
> 根据分类选择清除对应的ip段、清除所有认定为爬虫的

这个我思路是写了个SQL直接跑，后面也可以做成功能，但是还没想好。

https://zhaiyiming.com/archives/quick-delete-typecho-access-ip-logs.html


想了下可以做成功能，做一个特殊的过滤器，就叫 智能判断：无、疑似爬虫、疑似扫站

**Comment by tinymins** [comment]
> 



> > 根据分类选择清除对应的ip段、清除所有认定为爬虫的
> 
> 这个我思路是写了个SQL直接跑，后面也可以做成功能，但是还没想好。
> 
> https://zhaiyiming.com/archives/quick-delete-typecho-access-ip-logs.html
> 
> 想了下可以做成功能，做一个特殊的过滤器，就叫 智能判断：无、疑似爬虫、疑似扫站

@nuoxianCN 已实现

![image](https://user-images.githubusercontent.com/1808990/206653026-a614d32a-557f-47f0-8199-4cc1826926af.png)

**Comment by tinymins** [comment]
> > > 冲突的原因我解决了, 我删除了那个插件的检查更新的代码, 影响到咱们这个统计插件了, 我给它都删除就完事了. 现在剩下的这个应该是本身的问题了, 我搞不懂 -_-..
> > 
> > 
> > 不该冲突啊，我也试着安装了你提到的这个插件，是这个地址嘛 https://github.com/gogobody/SimpleAdmin
> 
> 给您添麻烦了, 是这个地址的, 冲突是我删除那个插件检测更新的代码造成的, 我已经解决了,
> 
> 我的 PHP 版本是 7.3.33, 下面那个代码改前和改后都是正常运行的.. 如果那个 访问日志->UA 是点击后显示所有相同记录的话, 那我这里就是全部正常了, 我之前以为是点击后 弹出那个 UA 的详细信息.. 再次感谢你...

已重新实现弹窗展示详情：

![image](https://user-images.githubusercontent.com/1808990/207015382-fae21992-7742-4999-b22a-fe65a77e61eb.png)
