### ISSUE TITLE
IPv6下访问导致Database Query Error

### ISSUE THREAD

**Issue by lydasia** [kokororin/typecho-plugin-Access#8]
如题。安装并启用插件后，使用IPv4网络访问正常，IPv6导致Database Query Error。

**Comment by kokororin** [comment]
可以贴出$_SERVER数组么，这里没有ipv6测试环境

**Comment by lydasia** [comment]
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1

Typecho_Db_Query_Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1 in /var/www/mydomin.com/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /var/www/mydomin.com/var/Typecho/Db.php(352): Typecho_Db_Adapter_Pdo->query(Object(Typecho_Db_Query), Object(PDO), 2, 'INSERT')
#1 /var/www/mydomin.com/usr/plugins/Access/Access_Core.php(238): Typecho_Db->query(Object(Typecho_Db_Query))
#2 /var/www/mydomin.com/usr/plugins/Access/Plugin.php(131): Access_Core->writeLogs()
#3 /var/www/mydomin.com/var/Typecho/Plugin.php(489): Access_Plugin::backend(Object(Widget_Archive), NULL)
#4 /var/www/mydomin.com/var/Widget/Archive.php(2012): Typecho_Plugin->__call('Widget_Archive:...', Array)
#5 /var/www/mydomin.com/var/Typecho/Router.php(138): Widget_Archive->render()
#6 /var/www/mydomin.com/index.php(23): Typecho_Router::dispatch()
#7 {main}

这应该很清楚了吧～
估计把varchar(16)改大点儿就没问题了

**Comment by lydasia** [comment]
嗯，试了下改成varchar(48)就没问题了。
![2017-05-15 9 27 52](https://cloud.githubusercontent.com/assets/22676960/26046853/2e494304-3951-11e7-9cb6-9198851dc67b.png)
![2017-05-15 9 27 34](https://cloud.githubusercontent.com/assets/22676960/26046856/312e2b98-3951-11e7-976b-82fa8c7618b8.png)

**Comment by lydasia** [comment]
不过查询接口可能得再做点修改
![2017-05-15 9 33 44](https://cloud.githubusercontent.com/assets/22676960/26046985/a8565556-3951-11e7-9d64-533cb633918e.png)

**Comment by kokororin** [comment]
因为用的是ipip.net本地库，所以暂不支持ipv6查询，好像在线版也不行

**Comment by lydasia** [comment]
IPv6的本地库就不考虑了吧。。我一般在RIPE家的数据库查，别家的我试过的好像都不太给力。不过这个插件已经相当赞了，这个功能也无关紧要。

**Comment by kokororin** [comment]
目前采用keycdn接口进行查询ipip.net没有的数据，不过国内应该被墙了。如果有更好的接口可以提供啦
